name: daily_safety_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  contacts_service: ^0.6.3
  permission_handler: ^11.3.0
  intl: ^0.19.0
  background_sms: ^0.0.1
  geolocator: ^11.0.0 # 위치 정보 획득을 위해 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # 만약 스마일 이미지를 사용하신다면 아래 주석을 풀고 경로를 맞춰주세요
  # assets:
  #   - assets/smile.png
